ci: combine release workflows

diff --git a/.github/workflows/publish-packages.yml b/.github/workflows/publish-packages.yml
--- a/.github/workflows/publish-packages.yml
+++ b/.github/workflows/publish-packages.yml
@@ -1,18 +1,18 @@
 name: Release packages
 on:
+  issue_comment:
+    types: [created]
   push:
     branches:
       - main
 
 permissions:
-  contents: read
-  pull-requests: read
+  id-token: write
+  pull-requests: write
+  contents: write
+  issues: write
 
 env:
-  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
-  AWS_DEFAULT_REGION: us-east-1
-  AWS_DEFAULT_OUTPUT: json
   SLACK_WEBHOOK_URL_VIC: ${{ secrets.SLACK_WEBHOOK_URL_VIC }}
   SLACK_WEBHOOK_URL_UIC: ${{ secrets.SLACK_WEBHOOK_URL_UIC }}
   SLACK_WEBHOOK_URL_ADK: ${{ secrets.SLACK_WEBHOOK_URL_ADK }}
@@ -20,13 +20,9 @@ env:
 
 jobs:
   release-affected-packages:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     name: Release affected packages
     runs-on: ubuntu-latest
-    permissions:
-      id-token: write
-      contents: write
-      issues: write
-      pull-requests: write
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -44,6 +40,9 @@ jobs:
         uses: 8BitJonny/gh-get-current-pr@3.0.0
         id: PR
 
+      - name: Update npm
+        run: npm install -g npm@latest
+
       - name: Install dependencies
         run: npm ci
 
@@ -55,9 +54,6 @@ jobs:
       - name: Get packages with version bump
         id: changed_pkgs
         run: bash scripts/get_pkgs_with_version_bump.sh
-
-      - name: Update npm
-        run: npm install -g npm@latest
 
       - name: Update versions and release packages
         env:
@@ -72,3 +68,89 @@ jobs:
           pr_title: ${{ steps.PR.outputs.pr_title }}
           pr_url: ${{ steps.PR.outputs.pr_url }}
         run: bash scripts/notify_version_released.sh
+
+  beta-release:
+    if: github.event.issue.pull_request && contains(github.event.comment.body, 'beta-release-bot:')
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+
+    steps:
+      - name: Get PR branch
+        uses: xt0rted/pull-request-comment-branch@v2
+        id: comment-branch
+
+      - name: Checkout PR branch
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          ref: ${{ steps.comment-branch.outputs.head_ref }}
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+          registry-url: https://registry.npmjs.org/
+          cache: npm
+
+      - name: Set referenced package
+        run: |
+          REFERENCED_PACKAGE=$(echo "${{ github.event.comment.body }}" | sed -n 's/.*beta-release-bot: \([^)]*\).*/\1/p')
+          echo "Referenced package: $REFERENCED_PACKAGE"
+          echo "REFERENCED_PACKAGE=$REFERENCED_PACKAGE" >> $GITHUB_ENV
+
+      - name: Confirm referenced package exists
+        run: |
+          if [ ! -d "./libs/$REFERENCED_PACKAGE" ]; then
+            echo "Error: Directory ./libs/$REFERENCED_PACKAGE does not exist."
+            exit 1
+          fi
+
+      - name: Update npm
+        run: npm install -g npm@latest
+
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Configure Git
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Get current beta version
+        id: beta_version
+        env:
+          REFERENCED_PACKAGE: ${{ env.REFERENCED_PACKAGE }}
+          GITHUB_REPOSITORY: ${{ github.repository }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: bash scripts/get_beta_version.sh
+
+      - name: Beta release package
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          AWS_REGION: us-east-1
+        run: |
+          npx nx build $REFERENCED_PACKAGE
+          cd dist/$REFERENCED_PACKAGE
+          npm version $beta_version --no-git-tag-version
+          npm publish --tag beta --access public
+
+      - name: Add comment to PR
+        uses: actions/github-script@v6
+        if: always()
+        with:
+          script: |
+            const workflow = '${{ github.workflow  }}';
+            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
+            const success = '${{ job.status }}' === 'success';
+            const pkg = process.env.REFERENCED_PACKAGE;
+            const version = process.env.beta_version;
+            let body = `[${workflow} (${pkg})](${url}): ${success ? 'Succeeded ✅' : 'Failed ❌'}`;
+            if (success) {
+              body = body + `\n\nTo install, run \`npm install @mathstack/${pkg}@${version}\``;
+            }
+            await github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: body
+            })
